// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XKMEAN_IP_H
#define XKMEAN_IP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xkmean_ip_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Slv0_BaseAddress;
} XKmean_ip_Config;
#endif

typedef struct {
    u32 Slv0_BaseAddress;
    u32 IsReady;
} XKmean_ip;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XKmean_ip_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XKmean_ip_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XKmean_ip_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XKmean_ip_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XKmean_ip_Initialize(XKmean_ip *InstancePtr, u16 DeviceId);
XKmean_ip_Config* XKmean_ip_LookupConfig(u16 DeviceId);
int XKmean_ip_CfgInitialize(XKmean_ip *InstancePtr, XKmean_ip_Config *ConfigPtr);
#else
int XKmean_ip_Initialize(XKmean_ip *InstancePtr, const char* InstanceName);
int XKmean_ip_Release(XKmean_ip *InstancePtr);
#endif

void XKmean_ip_Start(XKmean_ip *InstancePtr);
u32 XKmean_ip_IsDone(XKmean_ip *InstancePtr);
u32 XKmean_ip_IsIdle(XKmean_ip *InstancePtr);
u32 XKmean_ip_IsReady(XKmean_ip *InstancePtr);
void XKmean_ip_EnableAutoRestart(XKmean_ip *InstancePtr);
void XKmean_ip_DisableAutoRestart(XKmean_ip *InstancePtr);


void XKmean_ip_InterruptGlobalEnable(XKmean_ip *InstancePtr);
void XKmean_ip_InterruptGlobalDisable(XKmean_ip *InstancePtr);
void XKmean_ip_InterruptEnable(XKmean_ip *InstancePtr, u32 Mask);
void XKmean_ip_InterruptDisable(XKmean_ip *InstancePtr, u32 Mask);
void XKmean_ip_InterruptClear(XKmean_ip *InstancePtr, u32 Mask);
u32 XKmean_ip_InterruptGetEnabled(XKmean_ip *InstancePtr);
u32 XKmean_ip_InterruptGetStatus(XKmean_ip *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
