// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xkmean_ip.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XKmean_ip_CfgInitialize(XKmean_ip *InstancePtr, XKmean_ip_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Slv0_BaseAddress = ConfigPtr->Slv0_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XKmean_ip_Start(XKmean_ip *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKmean_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_AP_CTRL) & 0x80;
    XKmean_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_AP_CTRL, Data | 0x01);
}

u32 XKmean_ip_IsDone(XKmean_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKmean_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XKmean_ip_IsIdle(XKmean_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKmean_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XKmean_ip_IsReady(XKmean_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKmean_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XKmean_ip_EnableAutoRestart(XKmean_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKmean_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_AP_CTRL, 0x80);
}

void XKmean_ip_DisableAutoRestart(XKmean_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKmean_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_AP_CTRL, 0);
}

void XKmean_ip_InterruptGlobalEnable(XKmean_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKmean_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_GIE, 1);
}

void XKmean_ip_InterruptGlobalDisable(XKmean_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKmean_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_GIE, 0);
}

void XKmean_ip_InterruptEnable(XKmean_ip *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XKmean_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_IER);
    XKmean_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_IER, Register | Mask);
}

void XKmean_ip_InterruptDisable(XKmean_ip *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XKmean_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_IER);
    XKmean_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_IER, Register & (~Mask));
}

void XKmean_ip_InterruptClear(XKmean_ip *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKmean_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_ISR, Mask);
}

u32 XKmean_ip_InterruptGetEnabled(XKmean_ip *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XKmean_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_IER);
}

u32 XKmean_ip_InterruptGetStatus(XKmean_ip *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XKmean_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XKMEAN_IP_SLV0_ADDR_ISR);
}

