// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMM_IP_H
#define XMM_IP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmm_ip_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Slv0_BaseAddress;
} XMm_ip_Config;
#endif

typedef struct {
    u32 Slv0_BaseAddress;
    u32 IsReady;
} XMm_ip;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMm_ip_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMm_ip_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMm_ip_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMm_ip_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMm_ip_Initialize(XMm_ip *InstancePtr, u16 DeviceId);
XMm_ip_Config* XMm_ip_LookupConfig(u16 DeviceId);
int XMm_ip_CfgInitialize(XMm_ip *InstancePtr, XMm_ip_Config *ConfigPtr);
#else
int XMm_ip_Initialize(XMm_ip *InstancePtr, const char* InstanceName);
int XMm_ip_Release(XMm_ip *InstancePtr);
#endif

void XMm_ip_Start(XMm_ip *InstancePtr);
u32 XMm_ip_IsDone(XMm_ip *InstancePtr);
u32 XMm_ip_IsIdle(XMm_ip *InstancePtr);
u32 XMm_ip_IsReady(XMm_ip *InstancePtr);
void XMm_ip_EnableAutoRestart(XMm_ip *InstancePtr);
void XMm_ip_DisableAutoRestart(XMm_ip *InstancePtr);


void XMm_ip_InterruptGlobalEnable(XMm_ip *InstancePtr);
void XMm_ip_InterruptGlobalDisable(XMm_ip *InstancePtr);
void XMm_ip_InterruptEnable(XMm_ip *InstancePtr, u32 Mask);
void XMm_ip_InterruptDisable(XMm_ip *InstancePtr, u32 Mask);
void XMm_ip_InterruptClear(XMm_ip *InstancePtr, u32 Mask);
u32 XMm_ip_InterruptGetEnabled(XMm_ip *InstancePtr);
u32 XMm_ip_InterruptGetStatus(XMm_ip *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
