// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1ns/1ps

module mm_ip_out_r_if (
    // system singals
    input  wire        clk,
    input  wire        reset,
    // user signals
    input  wire [6:0]  out_r_address0,
    input  wire        out_r_ce0,
    input  wire        out_r_we0,
    input  wire [23:0] out_r_d0,
    // bus signals
    output wire        Clk_A,
    output wire        Rst_A,
    output wire        EN_A,
    output wire [3:0]  WEN_A,
    output wire [31:0] Addr_A,
    output wire [31:0] Dout_A,
    input  wire [31:0] Din_A
);
//------------------------Body---------------------------
assign Clk_A  = clk;
assign Rst_A  = reset;
assign EN_A   = out_r_ce0;
assign Addr_A = {out_r_address0, 2'b0};
assign WEN_A  = {4{out_r_we0}};
assign Dout_A = out_r_d0;

endmodule
