// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module mm_ip_top (
in_r_Clk_A,
in_r_Rst_A,
in_r_EN_A,
in_r_WEN_A,
in_r_Addr_A,
in_r_Dout_A,
in_r_Din_A,
out_r_Clk_A,
out_r_Rst_A,
out_r_EN_A,
out_r_WEN_A,
out_r_Addr_A,
out_r_Dout_A,
out_r_Din_A,
s_axi_slv0_AWADDR,
s_axi_slv0_AWVALID,
s_axi_slv0_AWREADY,
s_axi_slv0_WDATA,
s_axi_slv0_WSTRB,
s_axi_slv0_WVALID,
s_axi_slv0_WREADY,
s_axi_slv0_BRESP,
s_axi_slv0_BVALID,
s_axi_slv0_BREADY,
s_axi_slv0_ARADDR,
s_axi_slv0_ARVALID,
s_axi_slv0_ARREADY,
s_axi_slv0_RDATA,
s_axi_slv0_RRESP,
s_axi_slv0_RVALID,
s_axi_slv0_RREADY,
interrupt,
aresetn,
aclk
);

parameter C_S_AXI_SLV0_ADDR_WIDTH = 4;
parameter C_S_AXI_SLV0_DATA_WIDTH = 32;
parameter RESET_ACTIVE_LOW = 1;

output in_r_Clk_A ;
output in_r_Rst_A ;
output in_r_EN_A ;
output [4 - 1:0] in_r_WEN_A ;
output [32 - 1:0] in_r_Addr_A ;
output [32 - 1:0] in_r_Dout_A ;
input [32 - 1:0] in_r_Din_A ;


output out_r_Clk_A ;
output out_r_Rst_A ;
output out_r_EN_A ;
output [4 - 1:0] out_r_WEN_A ;
output [32 - 1:0] out_r_Addr_A ;
output [32 - 1:0] out_r_Dout_A ;
input [32 - 1:0] out_r_Din_A ;


input [C_S_AXI_SLV0_ADDR_WIDTH - 1:0] s_axi_slv0_AWADDR ;
input s_axi_slv0_AWVALID ;
output s_axi_slv0_AWREADY ;
input [C_S_AXI_SLV0_DATA_WIDTH - 1:0] s_axi_slv0_WDATA ;
input [C_S_AXI_SLV0_DATA_WIDTH/8 - 1:0] s_axi_slv0_WSTRB ;
input s_axi_slv0_WVALID ;
output s_axi_slv0_WREADY ;
output [2 - 1:0] s_axi_slv0_BRESP ;
output s_axi_slv0_BVALID ;
input s_axi_slv0_BREADY ;
input [C_S_AXI_SLV0_ADDR_WIDTH - 1:0] s_axi_slv0_ARADDR ;
input s_axi_slv0_ARVALID ;
output s_axi_slv0_ARREADY ;
output [C_S_AXI_SLV0_DATA_WIDTH - 1:0] s_axi_slv0_RDATA ;
output [2 - 1:0] s_axi_slv0_RRESP ;
output s_axi_slv0_RVALID ;
input s_axi_slv0_RREADY ;
output interrupt ;

input aresetn ;

input aclk ;


wire in_r_Clk_A;
wire in_r_Rst_A;
wire in_r_EN_A;
wire [4 - 1:0] in_r_WEN_A;
wire [32 - 1:0] in_r_Addr_A;
wire [32 - 1:0] in_r_Dout_A;
wire [32 - 1:0] in_r_Din_A;


wire out_r_Clk_A;
wire out_r_Rst_A;
wire out_r_EN_A;
wire [4 - 1:0] out_r_WEN_A;
wire [32 - 1:0] out_r_Addr_A;
wire [32 - 1:0] out_r_Dout_A;
wire [32 - 1:0] out_r_Din_A;


wire [C_S_AXI_SLV0_ADDR_WIDTH - 1:0] s_axi_slv0_AWADDR;
wire s_axi_slv0_AWVALID;
wire s_axi_slv0_AWREADY;
wire [C_S_AXI_SLV0_DATA_WIDTH - 1:0] s_axi_slv0_WDATA;
wire [C_S_AXI_SLV0_DATA_WIDTH/8 - 1:0] s_axi_slv0_WSTRB;
wire s_axi_slv0_WVALID;
wire s_axi_slv0_WREADY;
wire [2 - 1:0] s_axi_slv0_BRESP;
wire s_axi_slv0_BVALID;
wire s_axi_slv0_BREADY;
wire [C_S_AXI_SLV0_ADDR_WIDTH - 1:0] s_axi_slv0_ARADDR;
wire s_axi_slv0_ARVALID;
wire s_axi_slv0_ARREADY;
wire [C_S_AXI_SLV0_DATA_WIDTH - 1:0] s_axi_slv0_RDATA;
wire [2 - 1:0] s_axi_slv0_RRESP;
wire s_axi_slv0_RVALID;
wire s_axi_slv0_RREADY;
wire interrupt;

wire aresetn;



wire [8 - 1:0] sig_mm_ip_in_r_address0;
wire sig_mm_ip_in_r_ce0;
wire [24 - 1:0] sig_mm_ip_in_r_q0;


wire [7 - 1:0] sig_mm_ip_out_r_address0;
wire sig_mm_ip_out_r_ce0;
wire sig_mm_ip_out_r_we0;
wire [24 - 1:0] sig_mm_ip_out_r_d0;

wire sig_mm_ip_ap_start;
wire sig_mm_ip_ap_ready;
wire sig_mm_ip_ap_done;
wire sig_mm_ip_ap_idle;

wire sig_mm_ip_ap_rst;



mm_ip mm_ip_U(
    .in_r_address0(sig_mm_ip_in_r_address0),
    .in_r_ce0(sig_mm_ip_in_r_ce0),
    .in_r_q0(sig_mm_ip_in_r_q0),
    .out_r_address0(sig_mm_ip_out_r_address0),
    .out_r_ce0(sig_mm_ip_out_r_ce0),
    .out_r_we0(sig_mm_ip_out_r_we0),
    .out_r_d0(sig_mm_ip_out_r_d0),
    .ap_start(sig_mm_ip_ap_start),
    .ap_ready(sig_mm_ip_ap_ready),
    .ap_done(sig_mm_ip_ap_done),
    .ap_idle(sig_mm_ip_ap_idle),
    .ap_rst(sig_mm_ip_ap_rst),
    .ap_clk(aclk)
);

mm_ip_in_r_if mm_ip_in_r_if_U(
    .clk(aclk),
    .reset(sig_mm_ip_ap_rst),
    .in_r_address0(sig_mm_ip_in_r_address0),
    .in_r_ce0(sig_mm_ip_in_r_ce0),
    .in_r_q0(sig_mm_ip_in_r_q0),
    .Clk_A(in_r_Clk_A),
    .Rst_A(in_r_Rst_A),
    .EN_A(in_r_EN_A),
    .WEN_A(in_r_WEN_A),
    .Addr_A(in_r_Addr_A),
    .Dout_A(in_r_Dout_A),
    .Din_A(in_r_Din_A));

mm_ip_out_r_if mm_ip_out_r_if_U(
    .clk(aclk),
    .reset(sig_mm_ip_ap_rst),
    .out_r_address0(sig_mm_ip_out_r_address0),
    .out_r_ce0(sig_mm_ip_out_r_ce0),
    .out_r_we0(sig_mm_ip_out_r_we0),
    .out_r_d0(sig_mm_ip_out_r_d0),
    .Clk_A(out_r_Clk_A),
    .Rst_A(out_r_Rst_A),
    .EN_A(out_r_EN_A),
    .WEN_A(out_r_WEN_A),
    .Addr_A(out_r_Addr_A),
    .Dout_A(out_r_Dout_A),
    .Din_A(out_r_Din_A));

mm_ip_slv0_if #(
    .C_ADDR_WIDTH(C_S_AXI_SLV0_ADDR_WIDTH),
    .C_DATA_WIDTH(C_S_AXI_SLV0_DATA_WIDTH))
mm_ip_slv0_if_U(
    .ACLK(aclk),
    .ARESETN(aresetn),
    .I_ap_start(sig_mm_ip_ap_start),
    .O_ap_ready(sig_mm_ip_ap_ready),
    .O_ap_done(sig_mm_ip_ap_done),
    .O_ap_idle(sig_mm_ip_ap_idle),
    .AWADDR(s_axi_slv0_AWADDR),
    .AWVALID(s_axi_slv0_AWVALID),
    .AWREADY(s_axi_slv0_AWREADY),
    .WDATA(s_axi_slv0_WDATA),
    .WSTRB(s_axi_slv0_WSTRB),
    .WVALID(s_axi_slv0_WVALID),
    .WREADY(s_axi_slv0_WREADY),
    .BRESP(s_axi_slv0_BRESP),
    .BVALID(s_axi_slv0_BVALID),
    .BREADY(s_axi_slv0_BREADY),
    .ARADDR(s_axi_slv0_ARADDR),
    .ARVALID(s_axi_slv0_ARVALID),
    .ARREADY(s_axi_slv0_ARREADY),
    .RDATA(s_axi_slv0_RDATA),
    .RRESP(s_axi_slv0_RRESP),
    .RVALID(s_axi_slv0_RVALID),
    .RREADY(s_axi_slv0_RREADY),
    .interrupt(interrupt));

mm_ip_ap_rst_if #(
    .RESET_ACTIVE_LOW(RESET_ACTIVE_LOW))
ap_rst_if_U(
    .dout(sig_mm_ip_ap_rst),
    .din(aresetn));

endmodule
