// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsobel_ip.h"

extern XSobel_ip_Config XSobel_ip_ConfigTable[];

XSobel_ip_Config *XSobel_ip_LookupConfig(u16 DeviceId) {
	XSobel_ip_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSOBEL_IP_NUM_INSTANCES; Index++) {
		if (XSobel_ip_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSobel_ip_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSobel_ip_Initialize(XSobel_ip *InstancePtr, u16 DeviceId) {
	XSobel_ip_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSobel_ip_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSobel_ip_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

