// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module axi_interfaces_reverseBytes64 (
        in_r,
        ap_return
);

parameter    ap_true = 1'b1;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_28 = 32'b101000;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_37 = 32'b110111;
parameter    ap_const_lv32_38 = 32'b111000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_27 = 32'b100111;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input  [63:0] in_r;
output  [63:0] ap_return;

wire   [7:0] tmp_fu_43_p1;
wire   [7:0] tmp_1_fu_47_p4;
wire   [7:0] tmp_2_fu_57_p4;
wire   [7:0] tmp_9_fu_67_p4;
wire   [7:0] tmp_5_fu_107_p4;
wire   [7:0] tmp_s_fu_77_p4;
wire   [7:0] tmp_3_fu_87_p4;
wire   [7:0] tmp_4_fu_97_p4;



assign ap_return = {{{{{{{{tmp_fu_43_p1}, {tmp_1_fu_47_p4}}, {tmp_2_fu_57_p4}}, {tmp_9_fu_67_p4}}, {tmp_5_fu_107_p4}}, {tmp_s_fu_77_p4}}, {tmp_3_fu_87_p4}}, {tmp_4_fu_97_p4}};
assign tmp_1_fu_47_p4 = {{in_r[ap_const_lv32_F : ap_const_lv32_8]}};
assign tmp_2_fu_57_p4 = {{in_r[ap_const_lv32_17 : ap_const_lv32_10]}};
assign tmp_3_fu_87_p4 = {{in_r[ap_const_lv32_37 : ap_const_lv32_30]}};
assign tmp_4_fu_97_p4 = {{in_r[ap_const_lv32_3F : ap_const_lv32_38]}};
assign tmp_5_fu_107_p4 = {{in_r[ap_const_lv32_27 : ap_const_lv32_20]}};
assign tmp_9_fu_67_p4 = {{in_r[ap_const_lv32_1F : ap_const_lv32_18]}};
assign tmp_fu_43_p1 = in_r[7:0];
assign tmp_s_fu_77_p4 = {{in_r[ap_const_lv32_2F : ap_const_lv32_28]}};


endmodule //axi_interfaces_reverseBytes64

