// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfir_ip.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFir_ip_CfgInitialize(XFir_ip *InstancePtr, XFir_ip_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Slv0_BaseAddress = ConfigPtr->Slv0_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFir_ip_Start(XFir_ip *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFir_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_AP_CTRL) & 0x80;
    XFir_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_AP_CTRL, Data | 0x01);
}

u32 XFir_ip_IsDone(XFir_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFir_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XFir_ip_IsIdle(XFir_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFir_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XFir_ip_IsReady(XFir_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFir_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XFir_ip_EnableAutoRestart(XFir_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFir_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_AP_CTRL, 0x80);
}

void XFir_ip_DisableAutoRestart(XFir_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFir_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_AP_CTRL, 0);
}

void XFir_ip_InterruptGlobalEnable(XFir_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFir_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_GIE, 1);
}

void XFir_ip_InterruptGlobalDisable(XFir_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFir_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_GIE, 0);
}

void XFir_ip_InterruptEnable(XFir_ip *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFir_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_IER);
    XFir_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_IER, Register | Mask);
}

void XFir_ip_InterruptDisable(XFir_ip *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFir_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_IER);
    XFir_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_IER, Register & (~Mask));
}

void XFir_ip_InterruptClear(XFir_ip *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFir_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_ISR, Mask);
}

u32 XFir_ip_InterruptGetEnabled(XFir_ip *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFir_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_IER);
}

u32 XFir_ip_InterruptGetStatus(XFir_ip *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFir_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XFIR_IP_SLV0_ADDR_ISR);
}

