# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/EDA/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/Liucheng/Documents/scgra/cgra3x3_verification/cgra3x3_verification.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/Liucheng/Documents/scgra/cgra3x3_verification/cgra3x3_verification.srcs/sources_1/ip/blk_mem_gen_v7_3_13/coregen.cgc"

set ipFile "c:/Users/Liucheng/Documents/scgra/cgra3x3_verification/cgra3x3_verification.srcs/sources_1/ip/blk_mem_gen_v7_3_13/TrueDualPortBram256.xco"

set ipName "TrueDualPortBram256"

set hdlType "Verilog"

set cgPartSpec "xc7vx485t-1ffg1157"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "c:/Users/Liucheng/Documents/scgra/cgra3x3_verification/cgra3x3_verification.srcs/sources_1/ip/blk_mem_gen_v7_3_13/pa_cg_bom.xml"

# generate the IP
set result [source "c:/EDA/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

