#pragma line 1 "sobel_small/src/sobel_ip.c" ::: 0
#pragma line 1 "sobel_small/src/sobel_ip.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 147 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 13
#pragma line 238 "C:/EDA/Xilinx/Vivado_HLS/2013.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 20
#pragma line 9 "<command line>" 2 ::: 158
#pragma line 1 "<built-in>" 2 ::: 159
#pragma line 1 "sobel_small/src/sobel_ip.c" 2 ::: 160
#pragma line 1 "sobel_small/src/sobel.h" 1 ::: 161
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 1 3 ::: 162
#pragma line 10 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 173
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 176
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 187
#pragma line 18 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 193
#pragma line 62 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 207
#pragma line 10 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 214
#pragma line 32 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 218
#pragma line 147 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 221
#pragma line 225 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 225
#pragma line 247 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 227
#pragma line 277 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 229
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 230
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 244
#pragma line 674 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 250
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 251
#pragma line 674 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 252
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 254
#pragma line 675 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 255
#pragma line 13 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 256
#pragma line 46 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 276
#pragma line 102 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 278
#pragma line 277 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 280
#pragma line 316 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 284
#pragma line 370 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 290
#pragma line 380 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 292
#pragma line 392 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 294
#pragma line 405 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 296
#pragma line 418 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 298
#pragma line 428 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 300
#pragma line 456 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 311
#pragma line 518 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 331
#pragma line 605 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 345
#pragma line 12 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 2 3 ::: 409
#pragma line 55 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 415
#pragma line 79 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 420
#pragma line 91 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 422
#pragma line 135 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 456
#pragma line 162 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 475
#pragma line 260 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 535
#pragma line 278 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 542
#pragma line 325 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 567
#pragma line 372 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 581
#pragma line 403 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 589
#pragma line 552 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 711
#pragma line 583 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 733
#pragma line 594 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 735
#pragma line 737 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 805
#pragma line 871 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 901
#pragma line 898 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 913
#pragma line 1 "sobel_small/src/sobel.h" 2 ::: 915
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 917
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 927
#pragma line 9 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 933
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 936
#pragma line 11 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 944
#pragma line 26 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 948
#pragma line 84 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 960
#pragma line 120 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 979
#pragma line 157 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 981
#pragma line 312 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1127
#pragma line 330 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1135
#pragma line 373 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1171
#pragma line 417 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1206
#pragma line 475 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1236
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1271
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1281
#pragma line 9 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1287
#pragma line 509 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1288
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1291
#pragma line 511 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1299
#pragma line 2 "sobel_small/src/sobel.h" 2 ::: 1300
#pragma line 1 "sobel_small/src/sobel_ip.c" 2 ::: 1307
