#pragma line 1 "sobel_small/src/sobel_ip.c" ::: -10
#pragma line 1 "sobel_small/src/sobel_ip.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 3
#pragma line 238 "C:/EDA/Xilinx/Vivado_HLS/2013.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 10
#pragma line 9 "<command line>" 2 ::: 148
#pragma line 1 "<built-in>" 2 ::: 149
#pragma line 1 "sobel_small/src/sobel_ip.c" 2 ::: 150
#pragma line 1 "sobel_small/src/sobel.h" 1 ::: 151
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 1 3 ::: 152
#pragma line 10 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 163
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 166
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 177
#pragma line 18 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 183
#pragma line 62 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 197
#pragma line 10 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 204
#pragma line 32 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 208
#pragma line 147 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 211
#pragma line 225 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 215
#pragma line 247 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 217
#pragma line 277 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 219
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 220
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 234
#pragma line 674 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 240
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 241
#pragma line 674 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 242
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 244
#pragma line 675 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 245
#pragma line 13 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 246
#pragma line 46 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 266
#pragma line 102 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 268
#pragma line 277 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 270
#pragma line 316 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 274
#pragma line 370 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 280
#pragma line 380 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 282
#pragma line 392 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 284
#pragma line 405 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 286
#pragma line 418 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 288
#pragma line 428 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 290
#pragma line 456 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 301
#pragma line 518 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 321
#pragma line 605 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 335
#pragma line 12 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 2 3 ::: 399
#pragma line 55 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 405
#pragma line 79 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 410
#pragma line 91 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 412
#pragma line 135 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 446
#pragma line 162 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 465
#pragma line 260 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 525
#pragma line 278 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 532
#pragma line 325 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 557
#pragma line 372 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 571
#pragma line 403 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 579
#pragma line 552 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 701
#pragma line 583 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 723
#pragma line 594 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 725
#pragma line 737 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 795
#pragma line 871 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 891
#pragma line 898 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 903
#pragma line 1 "sobel_small/src/sobel.h" 2 ::: 905
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 907
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 917
#pragma line 9 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 923
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 926
#pragma line 11 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 934
#pragma line 26 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 938
#pragma line 84 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 950
#pragma line 120 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 969
#pragma line 157 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 971
#pragma line 312 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1117
#pragma line 330 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1125
#pragma line 373 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1161
#pragma line 417 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1196
#pragma line 475 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1226
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1261
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1271
#pragma line 9 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1277
#pragma line 509 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1278
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1281
#pragma line 511 "C:/EDA/Xilinx/Vivado_HLS/2013.3/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1289
#pragma line 2 "sobel_small/src/sobel.h" 2 ::: 1290
#pragma line 1 "sobel_small/src/sobel_ip.c" 2 ::: 1297
#pragma line 3 "sobel_small/src/sobel_ip.c" ::: 1302
#pragma line 3 "sobel_small/src/sobel_ip.c" ::: 1305
#pragma line 3 "sobel_small/src/sobel_ip.c" ::: 1308
#pragma line 22 "sobel_small/src/sobel_ip.c" ::: 1330
#pragma line 23 "sobel_small/src/sobel_ip.c" ::: 1334
#pragma line 42 "sobel_small/src/sobel_ip.c" ::: 1356
#pragma line 43 "sobel_small/src/sobel_ip.c" ::: 1360
