# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/base_sys_wrapper.xdc

# Block Designs: bd/base_sys/base_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys || ORIG_REF_NAME==base_sys}]

# IP: bd/base_sys/ip/base_sys_usr_dma_0_0/base_sys_usr_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_usr_dma_0_0 || ORIG_REF_NAME==base_sys_usr_dma_0_0}]

# IP: bd/base_sys/ip/base_sys_usr_dma_0_0/dma_ip/dma_ip.srcs/sources_1/ip/FIFO_16Bx64_prefetch/FIFO_16Bx64_prefetch.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_16Bx64_prefetch || ORIG_REF_NAME==FIFO_16Bx64_prefetch}]

# IP: bd/base_sys/ip/base_sys_processing_system7_0_0/base_sys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_processing_system7_0_0 || ORIG_REF_NAME==base_sys_processing_system7_0_0}]

# IP: bd/base_sys/ip/base_sys_acc_ip_0_0/base_sys_acc_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_acc_ip_0_0 || ORIG_REF_NAME==base_sys_acc_ip_0_0}]

# IP: bd/base_sys/ip/base_sys_processing_system7_0_axi_periph_0/base_sys_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==base_sys_processing_system7_0_axi_periph_0}]

# IP: bd/base_sys/ip/base_sys_rst_processing_system7_0_100M_0/base_sys_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==base_sys_rst_processing_system7_0_100M_0}]

# IP: bd/base_sys/ip/base_sys_xbar_0/base_sys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_xbar_0 || ORIG_REF_NAME==base_sys_xbar_0}]

# IP: bd/base_sys/ip/base_sys_axi_interconnect_0_0/base_sys_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_axi_interconnect_0_0 || ORIG_REF_NAME==base_sys_axi_interconnect_0_0}]

# IP: bd/base_sys/ip/base_sys_xlconcat_0_0/base_sys_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_xlconcat_0_0 || ORIG_REF_NAME==base_sys_xlconcat_0_0}]

# IP: bd/base_sys/ip/base_sys_xlconstant_0_0/base_sys_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_xlconstant_0_0 || ORIG_REF_NAME==base_sys_xlconstant_0_0}]

# IP: bd/base_sys/ip/base_sys_xlconstant_0_1/base_sys_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_xlconstant_0_1 || ORIG_REF_NAME==base_sys_xlconstant_0_1}]

# IP: bd/base_sys/ip/base_sys_xlconstant_0_2/base_sys_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_xlconstant_0_2 || ORIG_REF_NAME==base_sys_xlconstant_0_2}]

# IP: bd/base_sys/ip/base_sys_auto_pc_0/base_sys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_auto_pc_0 || ORIG_REF_NAME==base_sys_auto_pc_0}]

# IP: bd/base_sys/ip/base_sys_auto_pc_1/base_sys_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_auto_pc_1 || ORIG_REF_NAME==base_sys_auto_pc_1}]

# IP: bd/base_sys/ip/base_sys_auto_us_0/base_sys_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_auto_us_0 || ORIG_REF_NAME==base_sys_auto_us_0}]

# XDC: bd/base_sys/ip/base_sys_usr_dma_0_0/dma_ip/dma_ip.srcs/sources_1/ip/FIFO_16Bx64_prefetch/FIFO_16Bx64_prefetch/FIFO_16Bx64_prefetch.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_16Bx64_prefetch || ORIG_REF_NAME==FIFO_16Bx64_prefetch}] {/U0 }]/U0 ]]

# XDC: bd/base_sys/ip/base_sys_usr_dma_0_0/dma_ip/dma_ip.srcs/sources_1/ip/FIFO_16Bx64_prefetch/FIFO_16Bx64_prefetch_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_processing_system7_0_0/base_sys_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_sys_processing_system7_0_0 || ORIG_REF_NAME==base_sys_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/base_sys/ip/base_sys_rst_processing_system7_0_100M_0/base_sys_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_sys_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==base_sys_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/base_sys/ip/base_sys_rst_processing_system7_0_100M_0/base_sys_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_sys_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==base_sys_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/base_sys/ip/base_sys_rst_processing_system7_0_100M_0/base_sys_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_xbar_0/base_sys_xbar_0_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_auto_pc_0/base_sys_auto_pc_0_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_auto_pc_1/base_sys_auto_pc_1_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_auto_us_0/base_sys_auto_us_0_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_auto_us_0/base_sys_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_sys_auto_us_0 || ORIG_REF_NAME==base_sys_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/base_sys/base_sys_ooc.xdc
