# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "c:/EDA/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "D:/minibench/scgra/cgra5x5-verify/cgra5x5-verify.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "d:/minibench/scgra/cgra5x5-verify/cgra5x5-verify.srcs/sources_1/ip/blk_mem_gen_v7_3_5/coregen.cgc"

set ipFile "d:/minibench/scgra/cgra5x5-verify/cgra5x5-verify.srcs/sources_1/ip/blk_mem_gen_v7_3_5/data_buffer1.xco"

set ipName "data_buffer1"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "d:/minibench/scgra/cgra5x5-verify/cgra5x5-verify.srcs/sources_1/ip/blk_mem_gen_v7_3_5/pa_cg_bom.xml"

set cgPartSpec "xc7vx485t-1ffg1157"

set hdlType "Verilog"

# generate the IP
set result [source "c:/EDA/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

