############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 2013 Xilinx Inc. All rights reserved.
############################################################
open_project sobel_small
set_top sobel_ip
add_files sobel_small/src/sobel_ip.c
add_files -tb sobel_small/src/main.c
add_files -tb sobel_small/src/sobel.h
open_solution "unroll-1x2x3x3"
set_part {xc7z020clg484-1}
create_clock -period 10 -name default
source "./sobel_small/unroll-1x2x3x3/directives.tcl"
csim_design -clean
csynth_design
cosim_design -trace_level none
export_design -evaluate verilog -format ip_catalog -description "An IP generated by Vivado HLS" -vendor "xilinx.com" -library "hls" -version "1.0"
