######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "C:/Users/Liucheng/Documents/scgra_high_freq/scgra2x2_high_freq/scgra2x2_high_freq.srcs/sources_1/edk/base_sys"
if { [xload new base_sys.xmp] != 0 } {
  exit -1
}
xset arch zynq
xset dev xc7z020
xset package clg484
xset speedgrade -1

xset binfo ZEDBOARD

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl verilog
save proj
exit
