// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1ns/1ps

module fir_ip_sub_in_if (
    // system singals
    input  wire        clk,
    input  wire        reset,
    // user signals
    input  wire [7:0]  sub_in_address0,
    input  wire        sub_in_ce0,
    output wire [31:0] sub_in_q0,
    // bus signals
    output wire        Clk_A,
    output wire        Rst_A,
    output wire        EN_A,
    output wire [3:0]  WEN_A,
    output wire [31:0] Addr_A,
    output wire [31:0] Dout_A,
    input  wire [31:0] Din_A
);
//------------------------Body---------------------------
assign Clk_A     = clk;
assign Rst_A     = reset;
assign EN_A      = sub_in_ce0;
assign Addr_A    = {sub_in_address0, 2'b0};
assign WEN_A     = 4'b0;
assign Dout_A    = 32'b0;
assign sub_in_q0 = Din_A[31:0];

endmodule
