#!/bin/bash

App_Name="mm"
Type="medium"
Row="5"
Col="5"
CGRA_Size=$Row"x"$Col
DFG_Dir="/home/liucheng/gitrepo/project/benchmark/dump"
Scheduler_Dir="/home/liucheng/gitrepo/project/scheduler"
Bitfile_Dir="/home/liucheng/gitrepo/project/cgra/bitfile-update"

#Move DFG to Scheduler
cd $DFG_Dir
cp -rf $App_Name"-"$Type"/"*.* $Scheduler_Dir"/config/"

#Update configuration file
cd $Scheduler_Dir"/config/"
let Num=$Row*$Col
Link_Name="torus_"$Num"_"$CGRA_Size".txt"
rm "link.txt"
cp "$Link_Name" "link.txt"
sed -i "/^CGRA_scale/c\CGRA_scale $Num" "configure.txt"
sed -i "/^row/c\row $Row" "configure.txt"
sed -i "/^col/c\col $Col" "configure.txt"
sed -i "/^DFG_name/c\DFG_name $App_Name" "configure.txt"
cd ..
./cgracompiler

#Copy scheduling result as well as realted data to bitstream integration
cp -rf ./result/inst.mem $Bitfile_Dir"/"$App_Name"-"$Type".mem"
cp -rf ./result/src_ctrl_words.h $Bitfile_Dir"/dump"
cp -rf ./result/result_ctrl_words.h $Bitfile_Dir"/dump"
cp -rf ./config/io.h $Bitfile_Dir"/dump"

#Bitfile integration
cd $Bitfile_Dir
Bitfile="scgra"$CGRA_Size"-"$App_Name"-"$Type".bit"
Memfile=$App_Name"-"$Type".mem"
Modulename="scgra"$CGRA_Size"-1k"
echo $Modulename;
echo $Memfile
echo $Bitfile
echo $Row
echo $Col
./inst1k-update -t $Modulename -r $Row -c $Col -m $Memfile -e $Bitfile 
mv $Bitfile ./dump
