#pragma line 1 "kmean-small/src/kmean_ip.c" ::: -10
#pragma line 1 "kmean-small/src/kmean_ip.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/EDA/Xilinx/Vivado_HLS/2013.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 3
#pragma line 238 "C:/EDA/Xilinx/Vivado_HLS/2013.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 10
#pragma line 9 "<command line>" 2 ::: 148
#pragma line 1 "<built-in>" 2 ::: 149
#pragma line 1 "kmean-small/src/kmean_ip.c" 2 ::: 150
#pragma line 1 "kmean-small/src/kmean.h" 1 ::: 151
#pragma line 1 "kmean-small/src/kmean_ip.c" 2 ::: 161
#pragma line 3 "kmean-small/src/kmean_ip.c" ::: 166
#pragma line 3 "kmean-small/src/kmean_ip.c" ::: 169
#pragma line 3 "kmean-small/src/kmean_ip.c" ::: 172
#pragma line 20 "kmean-small/src/kmean_ip.c" ::: 192
#pragma line 20 "kmean-small/src/kmean_ip.c" ::: 195
