# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/EDA/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "D:/minibench/scgra/zc706/cgra2x2-tuning/cgra2x2-tuning.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "d:/minibench/scgra/zc706/cgra2x2-tuning/cgra2x2-tuning.srcs/sources_1/ip/blk_mem_gen_v7_3_0/coregen.cgc"

set ipFile "d:/minibench/scgra/zc706/cgra2x2-tuning/cgra2x2-tuning.srcs/sources_1/ip/blk_mem_gen_v7_3_0/IO_Buffer.xco"

set ipName "IO_Buffer"

set hdlType "Verilog"

set cgPartSpec "xc7z045-2ffg900"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "d:/minibench/scgra/zc706/cgra2x2-tuning/cgra2x2-tuning.srcs/sources_1/ip/blk_mem_gen_v7_3_0/pa_cg_bom.xml"

# generate the IP
set result [source "c:/EDA/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

