############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 2013 Xilinx Inc. All rights reserved.
############################################################
open_project mm-small
set_top mm_ip
add_files mm-small/src/mm_ip.c
add_files -tb mm-small/src/main.c
add_files -tb mm-small/src/mm_ip.h
open_solution "unroll_2x10x10"
set_part {xc7z020clg484-1}
create_clock -period 5 -name default
source "./mm-small/unroll_2x10x10/directives.tcl"
csim_design -clean
csynth_design
cosim_design -trace_level none
export_design -evaluate verilog -format ip_catalog -description "An IP generated by Vivado HLS" -vendor "xilinx.com" -library "hls" -version "1.0"
