webtalk_init -webtalk_dir /home/liucheng/projects/prj2016/dma_demo/dma_demo.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 6 16:25:51 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "qoojd33ims9uuilski0ht46s66" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1473146770000" -context "sdk\\\\hardware/1473146770000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1473146770000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1473146770000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1473146770000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1473146770000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1473146770000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1473146770000"
webtalk_add_data -client sdk -key uid -value "1473149541000" -context "sdk\\\\bsp/1473149541000"
webtalk_add_data -client sdk -key hwid -value "1473145986216" -context "sdk\\\\bsp/1473149541000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1473149541000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1473149541000"
webtalk_add_data -client sdk -key uid -value "1473149555000" -context "sdk\\\\application/1473149555000"
webtalk_add_data -client sdk -key hwid -value "1473145986216" -context "sdk\\\\application/1473149555000"
webtalk_add_data -client sdk -key bspid -value "1473149541000" -context "sdk\\\\application/1473149555000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1473149555000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1473149555000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1473149555000"
webtalk_add_data -client sdk -key uid -value "1473149656000" -context "sdk\\\\bsp/1473149656000"
webtalk_add_data -client sdk -key hwid -value "1473145986216" -context "sdk\\\\bsp/1473149656000"
webtalk_add_data -client sdk -key os -value "device_tree" -context "sdk\\\\bsp/1473149656000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1473149656000"
webtalk_transmit -clientid 3835630559 -regid "" -xml /home/liucheng/projects/prj2016/dma_demo/dma_demo.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/liucheng/projects/prj2016/dma_demo/dma_demo.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/liucheng/projects/prj2016/dma_demo/dma_demo.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
