#!/bin/bash


# Target function
matrix_array="4x4"
cgra_array="3x3"

# Switch to config directory, and then change the target DFG
cd ../config
rm MM.*
cp "mm"$matrix_array".txt" MM.txt
cp "mm"$matrix_array".s" MM.s

# Switch to the work directory and start the cgra compiler
cd ..
./cgracompiler

# Switch to the result directory and backup the result
cd result/"cgra"$cgra_array/"mm"$matrix_array
mv ../../*.* .

cd ../../../util

