# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/TDP_Data_Mem/TDP_Data_Mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TDP_Data_Mem || ORIG_REF_NAME==TDP_Data_Mem}]

# IP: ip/SP_Inst_Mem/SP_Inst_Mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SP_Inst_Mem || ORIG_REF_NAME==SP_Inst_Mem}]
