# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/EDA/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "D:/minibench/scgra-v1/cgra2x2-verify/cgra2x2-verify.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "d:/minibench/scgra-v1/cgra2x2-verify/cgra2x2-verify.srcs/sources_1/ip/blk_mem_gen_v7_3_0/coregen.cgc"

set ipFile "d:/minibench/scgra-v1/cgra2x2-verify/cgra2x2-verify.srcs/sources_1/ip/blk_mem_gen_v7_3_0/rom00.xco"

set ipName "rom00"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "d:/minibench/scgra-v1/cgra2x2-verify/cgra2x2-verify.srcs/sources_1/ip/blk_mem_gen_v7_3_0/pa_cg_bom.xml"

set cgPartSpec "xc7vx485t-1ffg1157"

set hdlType "Verilog"

# generate the IP
set result [source "c:/EDA/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

