######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

proc _main_ {} {
  cd "C:/Users/Liucheng/Documents/scgra_high_freq/scgra2x2_high_freq/scgra2x2_high_freq.srcs/sources_1/edk/base_sys"
  if { [ catch {xload xmp base_sys.xmp} result ] } {
    exit 10
  }

  # Set host application type
  xset intstyle PA

  if { [catch {run clean} result] } {
    return -1
  }
  return $result
}

# Cleanup generated data
if { [catch {_main_} result] } {
  exit -1
}

# Check return status and exit
if { [string length $result] == 0 } {
  exit 0
} else {
  exit $result
}
