# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.cache/wt [current_project]
set_property parent.project_path /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/base_sys.bd
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_processing_system7_0_0/base_sys_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_axi_cdma_0_0/base_sys_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_axi_cdma_0_0/base_sys_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_axi_bram_ctrl_0_0/base_sys_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_blk_mem_gen_0_0/base_sys_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_proc_sys_reset_0_0/base_sys_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_proc_sys_reset_0_0/base_sys_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_proc_sys_reset_0_0/base_sys_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_proc_sys_reset_1_0/base_sys_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_proc_sys_reset_1_0/base_sys_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_proc_sys_reset_1_0/base_sys_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_xbar_6/base_sys_xbar_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_auto_pc_0/base_sys_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/ip/base_sys_auto_pc_1/base_sys_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/base_sys_ooc.xdc]
set_property is_locked true [get_files /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/base_sys.bd]

read_verilog -library xil_defaultlib /home/liucheng/research/zynq-dev/cdma_demo/cdma_demo.srcs/sources_1/bd/base_sys/hdl/base_sys_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top base_sys_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef base_sys_wrapper.dcp

catch { report_utilization -file base_sys_wrapper_utilization_synth.rpt -pb base_sys_wrapper_utilization_synth.pb }
