# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/base_sys/base_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys || ORIG_REF_NAME==base_sys}]

# IP: bd/base_sys/ip/base_sys_processing_system7_0_0/base_sys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_processing_system7_0_0 || ORIG_REF_NAME==base_sys_processing_system7_0_0}]

# IP: bd/base_sys/ip/base_sys_axi_cdma_0_0/base_sys_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_axi_cdma_0_0 || ORIG_REF_NAME==base_sys_axi_cdma_0_0}]

# IP: bd/base_sys/ip/base_sys_axi_bram_ctrl_0_0/base_sys_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_axi_bram_ctrl_0_0 || ORIG_REF_NAME==base_sys_axi_bram_ctrl_0_0}]

# IP: bd/base_sys/ip/base_sys_blk_mem_gen_0_0/base_sys_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_blk_mem_gen_0_0 || ORIG_REF_NAME==base_sys_blk_mem_gen_0_0}]

# IP: bd/base_sys/ip/base_sys_proc_sys_reset_0_0/base_sys_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_proc_sys_reset_0_0 || ORIG_REF_NAME==base_sys_proc_sys_reset_0_0}]

# IP: bd/base_sys/ip/base_sys_proc_sys_reset_1_0/base_sys_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_proc_sys_reset_1_0 || ORIG_REF_NAME==base_sys_proc_sys_reset_1_0}]

# IP: bd/base_sys/ip/base_sys_axi_interconnect_1_0/base_sys_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_axi_interconnect_1_0 || ORIG_REF_NAME==base_sys_axi_interconnect_1_0}]

# IP: bd/base_sys/ip/base_sys_xbar_6/base_sys_xbar_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_xbar_6 || ORIG_REF_NAME==base_sys_xbar_6}]

# IP: bd/base_sys/ip/base_sys_processing_system7_0_axi_periph_3/base_sys_processing_system7_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_processing_system7_0_axi_periph_3 || ORIG_REF_NAME==base_sys_processing_system7_0_axi_periph_3}]

# IP: bd/base_sys/ip/base_sys_auto_pc_0/base_sys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_auto_pc_0 || ORIG_REF_NAME==base_sys_auto_pc_0}]

# IP: bd/base_sys/ip/base_sys_auto_pc_1/base_sys_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sys_auto_pc_1 || ORIG_REF_NAME==base_sys_auto_pc_1}]

# XDC: bd/base_sys/ip/base_sys_processing_system7_0_0/base_sys_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_sys_processing_system7_0_0 || ORIG_REF_NAME==base_sys_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/base_sys/ip/base_sys_axi_cdma_0_0/base_sys_axi_cdma_0_0_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_axi_cdma_0_0/base_sys_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_sys_axi_cdma_0_0 || ORIG_REF_NAME==base_sys_axi_cdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base_sys/ip/base_sys_axi_bram_ctrl_0_0/base_sys_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_blk_mem_gen_0_0/base_sys_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_proc_sys_reset_0_0/base_sys_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_sys_proc_sys_reset_0_0 || ORIG_REF_NAME==base_sys_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base_sys/ip/base_sys_proc_sys_reset_0_0/base_sys_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_sys_proc_sys_reset_0_0 || ORIG_REF_NAME==base_sys_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base_sys/ip/base_sys_proc_sys_reset_0_0/base_sys_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_proc_sys_reset_1_0/base_sys_proc_sys_reset_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_sys_proc_sys_reset_1_0 || ORIG_REF_NAME==base_sys_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: bd/base_sys/ip/base_sys_proc_sys_reset_1_0/base_sys_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_sys_proc_sys_reset_1_0 || ORIG_REF_NAME==base_sys_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: bd/base_sys/ip/base_sys_proc_sys_reset_1_0/base_sys_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_xbar_6/base_sys_xbar_6_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_auto_pc_0/base_sys_auto_pc_0_ooc.xdc

# XDC: bd/base_sys/ip/base_sys_auto_pc_1/base_sys_auto_pc_1_ooc.xdc

# XDC: bd/base_sys/base_sys_ooc.xdc
