// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmm_ip.h"

extern XMm_ip_Config XMm_ip_ConfigTable[];

XMm_ip_Config *XMm_ip_LookupConfig(u16 DeviceId) {
	XMm_ip_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMM_IP_NUM_INSTANCES; Index++) {
		if (XMm_ip_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMm_ip_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMm_ip_Initialize(XMm_ip *InstancePtr, u16 DeviceId) {
	XMm_ip_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMm_ip_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMm_ip_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

