// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmm_ip.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMm_ip_CfgInitialize(XMm_ip *InstancePtr, XMm_ip_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Slv0_BaseAddress = ConfigPtr->Slv0_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMm_ip_Start(XMm_ip *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMm_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_AP_CTRL) & 0x80;
    XMm_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMm_ip_IsDone(XMm_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMm_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMm_ip_IsIdle(XMm_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMm_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMm_ip_IsReady(XMm_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMm_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMm_ip_EnableAutoRestart(XMm_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMm_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_AP_CTRL, 0x80);
}

void XMm_ip_DisableAutoRestart(XMm_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMm_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_AP_CTRL, 0);
}

void XMm_ip_InterruptGlobalEnable(XMm_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMm_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_GIE, 1);
}

void XMm_ip_InterruptGlobalDisable(XMm_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMm_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_GIE, 0);
}

void XMm_ip_InterruptEnable(XMm_ip *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMm_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_IER);
    XMm_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_IER, Register | Mask);
}

void XMm_ip_InterruptDisable(XMm_ip *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMm_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_IER);
    XMm_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_IER, Register & (~Mask));
}

void XMm_ip_InterruptClear(XMm_ip *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMm_ip_WriteReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_ISR, Mask);
}

u32 XMm_ip_InterruptGetEnabled(XMm_ip *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMm_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_IER);
}

u32 XMm_ip_InterruptGetStatus(XMm_ip *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMm_ip_ReadReg(InstancePtr->Slv0_BaseAddress, XMM_IP_SLV0_ADDR_ISR);
}

