/*  zynqtimer.c - The simplest kernel module.
 */
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/irq.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("zynqtimer - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME        "zynqtimer"
#define TIMER_CNT           0x80000000
#define ZYNQ_TIMER_BASEADDR 0x42800000
#define ZYNQ_TIMER_HIGHADDR 0x4280FFFF
#define IRQ_NUM 61

#define ZYNQ_TIMER_TCSR_OFFSET		0x0
#define ZYNQ_TIMER_TLR_OFFSET		0x4
#define ZYNQ_TIMER_TCR_OFFSET		0x8

#define ZYNQ_TIMER_CSR_CASC_MASK        0x00000800
#define ZYNQ_TIMER_CSR_ENABLE_ALL_MASK	0x00000400
#define ZYNQ_TIMER_CSR_ENABLE_PWM_MASK	0x00000200
#define ZYNQ_TIMER_CSR_INT_OCCURED_MASK	0x00000100

#define ZYNQ_TIMER_CSR_ENABLE_TMR_MASK	0x00000080
#define ZYNQ_TIMER_CSR_ENABLE_INT_MASK	0x00000040
#define ZYNQ_TIMER_CSR_LOAD_MASK	    0x00000020
#define ZYNQ_TIMER_CSR_AUTO_RELOAD_MASK	0x00000010

#define ZYNQ_TIMER_CSR_EXT_CAPTURE_MASK	 0x00000008
#define ZYNQ_TIMER_CSR_EXT_GENERATE_MASK 0x00000004
#define ZYNQ_TIMER_CSR_DOWN_COUNT_MASK	 0x00000002
#define ZYNQ_TIMER_CSR_CAPTURE_MODE_MASK 0x00000001

static struct platform_device *pdev;
void *dev_virtaddr;
static int int_cnt;

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct zynqtimer_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

static irqreturn_t zynqtimer_irq(int irq, void *lp)
{
  unsigned int data;
  
  /* 
   * Check Timer Counter Value
   */
  data = ioread32(dev_virtaddr + ZYNQ_TIMER_TCR_OFFSET);
  printk("zynqtimer_irq: Interrupt Occurred ! Timer Count = 0x%08X\n",data);
  
  /* 
   * Clear Interrupt
   */
  data = ioread32(dev_virtaddr + ZYNQ_TIMER_TCSR_OFFSET);
  iowrite32(data | ZYNQ_TIMER_CSR_INT_OCCURED_MASK,
	    dev_virtaddr + ZYNQ_TIMER_TCSR_OFFSET);
  
  /* 
   * Disable Timer after 100 Interrupts
   */
  int_cnt++;
  
  if (int_cnt>=100)
    {
      printk("zynqtimer_irq: 100 interrupts have been occurred. Disabling timer");
      data = ioread32(dev_virtaddr + ZYNQ_TIMER_TCSR_OFFSET);
      iowrite32(data & ~(ZYNQ_TIMER_CSR_ENABLE_TMR_MASK), dev_virtaddr + ZYNQ_TIMER_TCSR_OFFSET);
    }
  
  return IRQ_HANDLED;
}

static int zynqtimer_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct zynqtimer_local *lp = NULL;

	int rc = 0;
	
	dev_info(dev, "Device Tree Probing\n");

	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	
	lp = (struct zynqtimer_local *) kmalloc(sizeof(struct zynqtimer_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate zynqtimer device\n");
		return -ENOMEM;
	}
	
	dev_set_drvdata(dev, lp);
	
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "zynqtimer: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "zynqtimer at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	
	rc = request_irq(lp->irq, &zynqtimer_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"zynqtimer at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int zynqtimer_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct zynqtimer_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id zynqtimer_of_match[] = {
	{ .compatible = "vendor,zynqtimer", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, zynqtimer_of_match);
#else
# define zynqtimer_of_match
#endif


static struct platform_driver zynqtimer_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= zynqtimer_of_match,
	},
	.probe		= zynqtimer_probe,
	.remove		= zynqtimer_remove,
};

static int __init zynqtimer_init(void)
{
  unsigned int data;
  
  int_cnt = 0;
  printk(KERN_INFO "zynqtimer_init: Initialize Module \"%s\"\n", DRIVER_NAME);
  
  /* 
   * Register ISR
   */
  if (request_irq(IRQ_NUM, zynqtimer_irq, 0, DRIVER_NAME, NULL)) {
    printk(KERN_ERR "zynqtimer_init: Cannot register IRQ %d\n", IRQ_NUM);
    return -EIO;
  }
  else {
    printk(KERN_INFO "zynqtimer_init: Registered IRQ %d\n", IRQ_NUM);
  }
  
  /* 
   * Map Physical address to Virtual address
   */
  dev_virtaddr = ioremap_nocache(ZYNQ_TIMER_BASEADDR,
				 ZYNQ_TIMER_HIGHADDR - ZYNQ_TIMER_BASEADDR + 1);
  
  /* 
   * Set Timer Counter
   */
  iowrite32(TIMER_CNT, dev_virtaddr + ZYNQ_TIMER_TLR_OFFSET);
  data = ioread32(dev_virtaddr + ZYNQ_TIMER_TLR_OFFSET);
  printk("zynqtimer_init: Set timer count 0x%08X\n",data);
  
  /* 
   * Set Timer mode and enable interrupt
   */  
  iowrite32(ZYNQ_TIMER_CSR_LOAD_MASK | ZYNQ_TIMER_CSR_INT_OCCURED_MASK, 
          dev_virtaddr + ZYNQ_TIMER_TCSR_OFFSET);
  data = ioread32(dev_virtaddr + ZYNQ_TIMER_TLR_OFFSET);
  iowrite32(data | ZYNQ_TIMER_CSR_ENABLE_INT_MASK | ZYNQ_TIMER_CSR_AUTO_RELOAD_MASK,
	    dev_virtaddr + ZYNQ_TIMER_TCSR_OFFSET);

  /* 
   * Register Device Module
   */
  pdev = platform_device_register_simple(DRIVER_NAME, 0, NULL, 0);              
  if (pdev == NULL) {                                                     
    printk(KERN_WARNING "zynqaxitimer_init: Adding platform device \"%s\" failed\n", DRIVER_NAME);
    kfree(pdev);                                                             
    return -ENODEV;                                                          
  }
  
  /* 
   * Start Timer
   */
  data = ioread32(dev_virtaddr + ZYNQ_TIMER_TCSR_OFFSET);
  iowrite32(data | ZYNQ_TIMER_CSR_ENABLE_TMR_MASK,
	    dev_virtaddr + ZYNQ_TIMER_TCSR_OFFSET);

  return 0;
}


static void __exit zynqtimer_exit(void)
{
    iounmap(dev_virtaddr);
    free_irq(IRQ_NUM, NULL);
    platform_device_unregister(pdev);                                             
    printk(KERN_INFO "zynqtimer_edit: Exit Device Module \"%s\".\n", DRIVER_NAME);
}

module_init(zynqtimer_init);
module_exit(zynqtimer_exit);

