// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfir_ip.h"

extern XFir_ip_Config XFir_ip_ConfigTable[];

XFir_ip_Config *XFir_ip_LookupConfig(u16 DeviceId) {
	XFir_ip_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFIR_IP_NUM_INSTANCES; Index++) {
		if (XFir_ip_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFir_ip_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFir_ip_Initialize(XFir_ip *InstancePtr, u16 DeviceId) {
	XFir_ip_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFir_ip_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFir_ip_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

