############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 2013 Xilinx Inc. All rights reserved.
############################################################
open_project kmean-small
set_top kmean_ip
add_files kmean-small/src/kmean_ip.c
add_files -tb kmean-small/src/kmean.h
add_files -tb kmean-small/src/main.c
open_solution "unroll-20"
set_part {xc7z020clg484-1}
create_clock -period 10 -name default
source "./kmean-small/unroll-20/directives.tcl"
csim_design -clean
csynth_design
cosim_design -trace_level none
export_design -evaluate verilog -format ip_catalog -description "An IP generated by Vivado HLS" -vendor "xilinx.com" -library "hls" -version "1.0"
