############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 2013 Xilinx Inc. All rights reserved.
############################################################
open_project axi_interfaces_prj
set_top axi_interfaces
add_files axi_interfaces.cpp
add_files -tb axi_interfaces_test.c
add_files -tb result.golden.dat
open_solution "solution1"
set_part {xc7k325tffg900-2}
create_clock -period 4 -name default
source "./axi_interfaces_prj/solution1/directives.tcl"
csim_design
csynth_design
cosim_design -trace_level none
export_design -format ip_catalog -description "An IP generated by Vivado HLS" -vendor "xilinx.com" -library "hls" -version "1.0"
