// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xkmean_ip.h"

extern XKmean_ip_Config XKmean_ip_ConfigTable[];

XKmean_ip_Config *XKmean_ip_LookupConfig(u16 DeviceId) {
	XKmean_ip_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XKMEAN_IP_NUM_INSTANCES; Index++) {
		if (XKmean_ip_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XKmean_ip_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XKmean_ip_Initialize(XKmean_ip *InstancePtr, u16 DeviceId) {
	XKmean_ip_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XKmean_ip_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XKmean_ip_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

