#!/bin/bash

###########################################################
# Initial directories
###########################################################

Scheduler_Dir=/home/liucheng/gitrepo/project/scheduler

###########################################################
# Read and check input options
###########################################################

if [ ! $# -ge 8 ]; then
    echo "The parameters must be provided in the following order!"
    echo "$0 [-n App_Name] [-r CGRA_Row] [-c CGRA_Column] [-l Pipeline] [-s Sim_Only]"
    exit 1
fi

if [ ! "$1" = "-n" ]; then
    echo "Unknown option $1"
    exit 1
fi
App_Name=$2

if [ ! "$3" = "-r" ]; then
    echo "Unknown option $3"
    exit 1
fi
Row=$4

if [ ! "$5" = "-c" ]; then
    echo "Unknown option $5"
    exit 1
fi
Col=$6

if [ ! "$7" = "-l" ]; then
    echo "Unknown option $7"
    exit 1
fi
Pipeline=$8

if [ $# -gt 8 ]; then
    if [ ! "$9" = "-s" ]; then
        echo "Unknown option $9"
        exit 1
    fi
    shift
    Sim_Only=$9

fi

CGRA_Size=$Row"x"$Col

###########################################################
# DFG Scheduling
###########################################################

#Start_Time=$(date +%s%N)
cd $Scheduler_Dir"/config/"
let Num=$Row*$Col 
let Max_IO_Buffer=65536
sed -i "/^CGRA_Scale/c\CGRA_Scale $Num" configure.txt
sed -i "/^Row/c\Row $Row" configure.txt
sed -i "/^Col/c\Col $Col" configure.txt
sed -i "/^DFG_Name/c\DFG_Name $App_Name" configure.txt
sed -i "/^Pipeline_Intensity/c\Pipeline_Intensity $Pipeline" configure.txt
if [ $Sim_Only -eq 1 ]; then
    sed -i "/^In_Buffer_Depth/c\In_Buffer_Depth $Max_IO_Buffer" configure.txt
    sed -i "/^Out_Buffer_Depth/c\Out_Buffer_Depth $Max_IO_Buffer" configure.txt
    sed -i "/^Impl_Or_Sim/c\Impl_Or_Sim 0" configure.txt
fi
cd ..
./cgracompiler 

#echo "DFG scheduling completes, time elapsed $((($End_Time - $Start_Time)/1000000))""ms"


