############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 2013 Xilinx Inc. All rights reserved.
############################################################
open_project fir-small
set_top fir_ip
add_files fir-small/src/fir_ip.c
add_files -tb fir-small/src/main.c
add_files -tb fir-small/src/fir_ip.h
open_solution "unroll-2x50"
set_part {xc7z020clg484-1}
create_clock -period 10 -name default
source "./fir-small/unroll-2x50/directives.tcl"
csim_design -clean
csynth_design
cosim_design -trace_level none
export_design -evaluate verilog -format ip_catalog -description "An IP generated by Vivado HLS" -vendor "xilinx.com" -library "hls" -version "1.0"
